services:
  db:
    image: postgres:17
    container_name: odoo-db
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 5s
      timeout: 5s
      retries: 5

  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    image: odoo-custom:19.0
    container_name: odoo-app
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8069"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: odoo
      DB_PASSWORD: odoo
    volumes:
      - odoo-data:/var/lib/odoo
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: odoo-nginx
    depends_on:
      - odoo
    ports:
      - "8069:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - nginx-logs:/var/log/nginx
    restart: unless-stopped

volumes:
  pgdata:
  odoo-data:
  nginx-logs:
